---

name: Build with CMake on Windows

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build preset '${{ matrix.cmake_preset }}' in '${{ matrix.cmake_build_configuration }}' configuration"

    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [windows-2025, windows-11-arm]
        cmake_build_configuration: [release, debug]

        include:
          - os: windows-2025
            cmake_preset: windows-x64-vs2022
            cmake_build_configuration: release
          - os: windows-2025
            cmake_preset: windows-x64-vs2022
            cmake_build_configuration: debug
          - os: windows-11-arm
            cmake_preset: windows-arm64-vs2022
            cmake_build_configuration: release
        exclude:
          - os: windows-11-arm
            cmake_build_configuration: debug

    steps:
    - uses: actions/checkout@v4

    - name: Set Reusable Strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      run: |
        chcp 65001 # Set code page to UTF-8.
        echo "build-output-dir=${{ github.workspace }}\build" >> $env:GITHUB_OUTPUT

    - name: Set Environment Variables
      run: |
        chcp 65001 # Set code page to UTF-8.
        echo ("VCPKG_ROOT=" + $env:VCPKG_INSTALLATION_ROOT) >> $env:GITHUB_ENV

    - name: Configure with CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }} --preset ${{ matrix.cmake_preset }}

    - name: Build with CMake
      run: |
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --preset ${{ matrix.cmake_preset }}-${{ matrix.cmake_build_configuration }}
