---

name: CMake Format and Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This job checks that the CMake files are formatted correctly.
  check-cmake-format:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # TODO: Pin the version of run-cmake-format to a specific commit or tag.
    - uses: Si1ver/run-cmake-format@main
      with:
        command: format
        path: '.'
        apply-formatting: false

  # This job runs cmake-lint to check the CMake files for issues.
  run-cmake-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # TODO: Pin the version of run-cmake-format to a specific commit or tag.
    - uses: Si1ver/run-cmake-format@main
      with:
        command: lint
        path: '.'
        lint-log-level: info

  # This job creates a pull request to update the CMake files if they are not formatted correctly.
  create-cmake-format-pr:
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name != github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # TODO: Pin the version of run-cmake-format to a specific commit or tag.
    - uses: Si1ver/run-cmake-format@main
      with:
        command: format
        path: '.'
        apply-formatting: true
    - uses: peter-evans/create-pull-request@v7
      with:
        title: '[Automated] CMake Format Update'
        body: |
          This pull request updates the CMake files to be formatted correctly.

          This is an automated pull request.
        commit-message: 'Update CMake files to be formatted correctly'
        branch: ${{ github.ref_name }}-automated-cmake-format
        labels: |
          format
          automated pr
        delete-branch: true